name: Deploy backend VM Docker

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig.json"
      - ".github/workflows/azure-backend-app-service.yml"

concurrency:
  group: deploy-backend-appservice-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_vm_docker_backend:
    uses: ./.github/workflows/reusable-deploy-vm-docker.yml
    with:
      deploy_scope: "backend"
